import React from 'react';
import { Link } from 'react-router-dom';

//Images
import Icon9 from '../../../assets/images/icons/icon9.svg';
import Icon10 from '../../../assets/images/icons/icon10.svg';
import Icon11 from '../../../assets/images/icons/icon11.svg';
import Icon12 from '../../../assets/images/icons/icon12.svg';
import Icon13 from '../../../assets/images/icons/icon13.svg';
import pic1 from '../../../assets/images/about/pic1.jpg';
import support1 from '../../../assets/images/icons/support1.png';

import analysis from '../../../assets/images/icons/analysis.svg';
import visualization from '../../../assets/images/icons/visualization.svg';
import forecast from '../../../assets/images/icons/forecast.svg';
import userInterface from '../../../assets/images/icons/user-interface.svg';
import success from '../../../assets/images/icons/success.jpeg';
import successIcon from '../../../assets/images/icons/success-icon.svg';

const cardData = [
  { image: userInterface, title: 'Convenient UI', info: 'Our Convenient UI is designed to streamline your cryptocurrency analysis and visualization experience. We aim to empower users of all backgrounds and expertise levels to easily access and interpret market metrics, make data-driven decisions, and utilize neural network-based price predictions effectively.' },
  { image: Icon10, title: 'Web-accessibility', info: 'The Web Accessibility (Web-A11y) section of our website is dedicated to ensuring that our analysis and visualization platform for cryptocurrency metrics, including price predictions generated by neural networks, is accessible to all users, regardless of their abilities or disabilities.' },
  { image: analysis, title: 'Analysis', info: 'Whether you\'re a seasoned cryptocurrency enthusiast or a beginner looking to enter the market, our Analysis section equips you with the tools and information you need to navigate the complex world of cryptocurrencies. Stay ahead of the curve, make informed decisions, and unlock the potential of this exciting digital asset class with our comprehensive analysis and visualization capabilities.' },
  { image: visualization, title: 'Visualization', info: 'Our visualization tools are designed to be user-friendly, even for those who are new to cryptocurrency analysis. We prioritize simplicity and clarity, making it easy for anyone to interpret and draw insights from the visual representations. You don\'t need to be a data expert to benefit from the power of visualization on our platform.' },
  { image: forecast, title: 'Prediction', info: 'Our Prediction section is seamlessly integrated with our analysis and visualization tools, allowing you to compare predictions with historical data and visualize the projected price trends. This holistic approach enables you to gain a comprehensive understanding of the market dynamics and make well-informed decisions' }
];

function OneStop() {
  return (
    <>
      {cardData.map((item, ind) => (
        <div className="col-xl-4 col-md-6 m-b60" key={ind}>
          <div className="icon-bx-wraper style-3">
            <div className="icon-media">
              <img src={item.image} alt="" width={100} />
            </div>
            <div className="icon-content">
              <h4 className="title text-center">{item.title}</h4>
              <p className="m-b0">
                {item.info}
              </p>
            </div>
          </div>
        </div>
      ))}
      <div className="col-xl-4 col-md-6 m-b60">
        <div className="icon-bx-wraper style-4" style={{ backgroundImage: 'url(' + success + ')' }}>
          <div className="inner-content">
            <div className="icon-media m-b30">
              <img src={successIcon} width={100} alt="" />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
export default OneStop;
